<?php


$title = 'Edit track';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$track = $form->get('title');
$track->setAttribute('class', 'form-control');
$track->setAttribute('placeholder', 'Track title');

$length = $form->get('length');
$length->setAttribute('class', 'form-control');
$length->setAttribute('placeholder', 'Track length');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', [
    'action' => 'edittrack',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($track) ?>
    <?= $this->formElement($track) ?>
    <?= $this->formElementErrors()->render($track, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($length) ?>
    <?= $this->formElement($length) ?>
    <?= $this->formElementErrors()->render($length, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('album'));
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();