<?php

$title = 'Add new track';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php
$track = $form->get('title');
$track->setAttribute('class', 'form-control');
$track->setAttribute('placeholder', 'Track title');

$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

$album = $form->get('album');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

$length = $form->get('length');
$length->setAttribute('class', 'form-control');
$length->setAttribute('placeholder', 'Track length');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('track', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($track) ?>
    <?= $this->formElement($track) ?>
    <?= $this->formElementErrors()->render($track, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($artist) ?>
    <?= $this->formElement($artist) ?>
    <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($album) ?>
    <?= $this->formElement($album) ?>
    <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($length) ?>
    <?= $this->formElement($length) ?>
    <?= $this->formElementErrors()->render($length, ['class' => 'help-block']) ?>
</div>


<?php
echo $this->formHidden($form->get('id'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();