<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div>
    
    <?php if (!$this->lmcUserIdentity()) : ?>
        <?= $this->lmcUserLoginWidget(); ?>
    <?php else : ?>
        <h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->lmcUserDisplayName() ?>!</h3>    
        <a href="<?php echo $this->url('lmcuser/logout') ?>"><?php echo $this->translate('Sign Out'); ?></a>
        <a href="<?php echo $this->url('lmcuser/changepassword') ?>"><?php echo $this->translate('Change Password'); ?></a>
    <?php endif ?>
</div>
